- name: Install latest golang
  become: true
  apt:
    name: golang-go
    state: present

- name: Add golang {{ golang.version }} to PATH
  include: roles/bashrc/tasks/bashrc_template.yml name=golang-path src=templates/golang-path.sh priority=20
