- name: Install dependencies commonly used by Python modules
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - libxml2-dev
    - libxslt-dev
    - swig

- name: Install Python code quality tools
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - pyflakes
    - pylint
    - pep8

- name: Install pip globally
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - python-pip
    - python3-pip

- name: Install virtualenv globally
  become: true
  pip:
    name: virtualenv

- name: Install virtualenv globally
  become: true
  pip:
    name: virtualenv
    executable: pip3

- name: Install IPython
  become: true
  apt:
      name: ipython
      state: present

