---
- name: Install zsh
  become: true
  apt:
    name: zsh
    state: present

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh"

- include: roles/dotfiles/tasks/symlink.yml src=.zshrc force=true

- name: Set ZSH as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/zsh"
