---
- name: Check if Spotify is already installed
  shell: "snap list | grep -q spotify"
  register: spotify_installed
  ignore_errors: true

- name: Install Spotify
  become: true
  command: "snap install spotify"
  when: "spotify_installed is failed"

