---
- name: Install i3 window manager
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - i3
    - i3status
    - dmenu
    - xbacklight
    - feh
    - conky
    - scrot

- include: roles/dotfiles/tasks/symlink.yml src=.config/i3 force=yes

